### ISSUE TITLE
在宏定义write中如果数字超过10，会导致错误，此为修改后的代码。

### ISSUE THREAD

**Issue by Hats-Wang** [mhq1065/Assembly#1]
int 21H
    mov dl,1[dst]
    int 21H
ENDM

code segment
assume cs:code,ds:data
main proc far

    mov ax,data
    mov ds,ax
   
    xor cx,cx
    xor dx,dx
    mov ah,01H
    int 1AH
    
    call subprogram

    mov ah,00H
    int 1AH

    ;获取秒数
    mov ax,dx
    mov dx,cx
    mov bx,18
    div bx
    ;获取时分秒
    mov bx,60
    mov dx,0
    div bl
   
    mov se,ah
    mov ah,0
    div bl
    mov mm,ah
    mov hh,al

    WRITE hh,shh
    mov dl,':'
    int 21h
    WRITE mm,smm
    mov dl,':'
    int 21h
    WRITE se,sss
    

    mov ax,4c00h
    int 21h
main endp

subprogram proc
    push cx
     push dx
     mov dx, 2000
loop1:
             mov cx , 20000
loop2:  loop loop2  
            dec dx
             jnz loop1
      pop dx
     pop cx
    ret
subprogram endp

**Comment by mhq1065** [comment]
> ```
> int 21H
> mov dl,1[dst]
> int 21H
> ```
> 
> ENDM
> 
> code segment
> assume cs:code,ds:data
> main proc far
> 
> ```
> mov ax,data
> mov ds,ax
> 
> xor cx,cx
> xor dx,dx
> mov ah,01H
> int 1AH
> 
> call subprogram
> 
> mov ah,00H
> int 1AH
> 
> ;获取秒数
> mov ax,dx
> mov dx,cx
> mov bx,18
> div bx
> ;获取时分秒
> mov bx,60
> mov dx,0
> div bl
> 
> mov se,ah
> mov ah,0
> div bl
> mov mm,ah
> mov hh,al
> 
> WRITE hh,shh
> mov dl,':'
> int 21h
> WRITE mm,smm
> mov dl,':'
> int 21h
> WRITE se,sss
> 
> 
> mov ax,4c00h
> int 21h
> ```
> 
> main endp
> 
> subprogram proc
> push cx
> push dx
> mov dx, 2000
> loop1:
> mov cx , 20000
> loop2: loop loop2
> dec dx
> jnz loop1
> pop dx
> pop cx
> ret
> subprogram endp

确实存在这个问题，因此我刚刚将时间转化为10进制输出，规避了16进制的问题。输入16进制可以参照  [code4_2 ](https://github.com/mhq1065/Assembly/blob/master/code4_2.asm)  中的宏定义

**Comment by Hats-Wang** [comment]
ok改了就行
